aptreiter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.main, name='main'),
    path('<str:slug>/', views.submenu, name='submenu'),
    path('<str:slug>/<str:submenu_slug>/', views.submenu_do_something, name='submenu_do_something'),
]

menu/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    """Описание каждого поля Меню"""
    title = models.CharField(max_length=120, verbose_name='Название')
    slug = models.SlugField(max_length=120, unique=True, verbose_name='EN. Адрес')
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE, verbose_name='Раздел')

    class Meta:
        verbose_name_plural = 'Меню'
        verbose_name = 'Меню'

    def __str__(self):
        return self.title
    
    def get_submenu(self):
        return self.menu_set.get_queryset()

class MenuItem(Menu):
    """Модель, создает экземпляр у основного меню"""
    class Meta:
        verbose_name_plural = 'Подменю'
        verbose_name = 'Подменю'
        proxy = True

menu/views.py
from django.shortcuts import render
from .models import *


def main(request):
    # Главная функция вывода основного дерева
    menus = Menu.objects.filter(parent=None)

    context = {
        'menus':menus
    }
    return render(request, 'menu/main.html', context)

def submenu(request, slug):
    # Функция вывода подменю
    context = {
        'main_slug':slug,
    }
    return render(request, 'menu/submenus.html', context)

def submenu_do_something(request, slug, submenu_slug):
    # Переход на ветку дерева подменю
    context = {
        'main_slug':slug,
        'active_link':submenu_slug,
    }
    return render(request, 'menu/submenus.html', context)

menu/templates/menu/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Menu{% endblock title %}</title>
</head>

<body>
    {% block tree %}
    <nav>
        <ul>
            {% for menu in menus %}
            <li><a href="{% url 'menu:submenu' menu.slug %}">{{ menu }}</a></li>
            {% empty %}
            Нет разделов
            {% endfor %}
        </ul>
    </nav>
    {% endblock tree %}

</body>
</html>

menu/templates/menu/submenus.html
{% extends 'menu/main.html' %}
{% load static %}
{% load menu_tree_filter %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ main_slug }}{% endblock title %}</title>
</head>
<body>
    {% block tree %}
    <nav>
        {% draw_menu main_slug active_link %}
    </nav>
    {% endblock tree %}
</body>
</html>

menu/templates/templatetags/menu.html
{% load menu_tree_filter %}

{% if menu.main %}
    <nav>
        <ul>
            {% for submenu in menu.submenu %}
            <li class="{% if submenu.slug in menu.parents_active_link %}active{% endif %}">
                <a href="{% url 'menu:submenu_do_something' menu.main.slug submenu.slug %}">{{ submenu }}</a>
                {% draw_submenu submenu menu.parents_active_link %}
            </li>
            {% endfor %}
        </ul>
    </nav>
{% else %}
    <p>{{ menu.error }}</p>
{% endif %}

menu/templates/templatetags/submenu.html
{% load menu_tree_filter %}
{% load static %}

<ul>
    {% for sub_menu in submenu_and_parents.submenu.get_submenu %}
    <li class="{% if sub_menu.slug in submenu_and_parents.parents_active_link %}active{% endif %}">
        <a href="{% url 'menu:submenu_do_something' submenu_and_parents.main sub_menu.slug %}">{{ sub_menu }}</a>
        {% draw_submenu sub_menu submenu_and_parents.parents_active_link %}
    </li>
    {% endfor %}
</ul>